# Generated by Django 3.2.15 on 2022-09-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["complete", "-updated_at", "-created_at"]},
        ),
        migrations.RenameField(
            model_name="task",
            old_name="create",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
